from django.conf.urls import  include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.views.static import serve
from django.urls import path
from rest_framework_simplejwt import views as jwt_views

ACCESS_CONTROL_ALLOW_ORIGIN = '*'
urlpatterns = [
	# url(r'^auth-jwt/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
	url(r'^auth-jwt/', views.MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    url(r'^token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    url(r'^token/verify/', jwt_views.TokenVerifyView.as_view(), name='token_verify'),
	path('hello/', views.HelloView.as_view(), name='hello'),
	
	url(r'^$', views.home_index, name='home_index'),
	url(r'^home/', views.home_index, name='home_index'),
	url(r'^login-submit/', views.login_user_submit.as_view(), name='login_user_submit'),
	url(r'^forgotpasswordsubmit/', views.forgot_password_submit.as_view(), name='forgot_password_submit'),
	url(r'^reset-password-submit/', views.reset_password_submit.as_view(), name='reset_password_submit'),
	url(r'^logout/', views.logout_page, name='logout_page'),
	url(r'^register-user/', views.register_user.as_view(), name='register_user'),
	url(r'^activation/(?P<base64string>\d+)/', views.activate_link, name='activate_link'),
	url(r'^dashboard/', views.user_profile.as_view(), name='user_profile'),
	url(r'^editprofile/', views.profile_edit.as_view(), name='profile_edit'),
	url(r'^share_opportunity_mail/', views.share_opportunity_mail.as_view(), name='share_opportunity_mail'),
	# url(r'^becomecoordinator/', views.becomecoordinator, name='becomecoordinator'),
	# url(r'^become-coordinator/', views.become_coordinator, name='become_coordinator'),
	url(r'^fblogin/', views.facebook_login, name='facebook_login'),
    url(r'^gplogin/', views.google_login, name='google_login'),
    url(r'^change_password/', views.change_password.as_view(), name='change_password'),
	url(r'^activity_categories/', views.get_activity_categories, name='get_activity_categories'),
	url(r'^get_organizations/', views.get_organizations, name='get_organizations'),
	url(r'^get_organization_by_name/', views.get_organization_by_name, name='get_organization_by_name'),
	url(r'^update_role/',views.update_role.as_view(), name='update_role'),
	url(r'^approve_coordinator_request/', views.approve_coordinator_request.as_view(), name='approve_coordinator_request'),
	url(r'^approve_organization_request/', views.approve_organization_request.as_view(), name='approve_organization_request'),
	# url(r'^get_organization_name/', views.get_organization_name, name='get_organization_name'),
	url(r'^get_opportunity_by_user/', views.get_opportunity_by_user.as_view(), name='get_opportunity_by_user'),
	url(r'^add_activity_category/', views.add_activity_category.as_view(), name='add_activity_category'),
	url(r'^add_opportunity/', views.add_opportunity.as_view(), name='add_opportunity'),
	url(r'^add_organiztion/', views.add_organiztion.as_view(), name='add_organiztion'),
	url(r'^add_volunteer/', views.add_volunteer.as_view(), name='add_volunteer'),
	url(r'^get_volunteers/', views.get_volunteers.as_view(), name='get_volunteers'),
	url(r'^get_opportunities/(?P<offset>\d+)/', views.get_opportunities, name='get_opportunities'),
	url(r'^get_opportunity_by_id/', views.get_opportunity_by_id.as_view(), name='get_opportunity_by_id'),
	url(r'^get_opportunitiesfiltered/(?P<offset>\d+)/', views.get_opportunitiesfiltered, name='get_opportunitiesfiltered'),
    url(r'^get_opportunity_by_user_date/', views.get_opportunity_by_user_date.as_view(), name='get_opportunity_by_user_date'),
    url(r'^add_activity/', views.add_activity.as_view(), name='add_activity'),
	url(r'^edit_activity/', views.edit_activity.as_view(), name='edit_activity'),
	url(r'^get_activities/', views.get_activities, name='get_activities'),
	url(r'^get_activity/', views.get_activity, name='get_activity'),
	url(r'^add_volunteersactivities/', views.add_volunteersactivities.as_view(), name='add_volunteersactivities'),
	url(r'^get_volunteersactivities/', views.get_volunteersactivities, name='get_volunteersactivities'),
	url(r'^get_statistics/', views.get_statistics.as_view(), name='get_statistics'),
	url(r'^get_opportunities_by_user/', views.get_opportunities_by_user.as_view(), name='get_opportunities_by_user'),
	url(r'^get-organization-by-user/', views.get_organization_by_user.as_view(), name='get_organization_by_user'),
	url(r'^submit-volenteer-request/', views.submit_volenteer_request.as_view(), name='submit_volenteer_request'),
	url(r'^apply-volunteer/', views.apply_volunteer.as_view(), name='apply_volunteer'),
	url(r'^get_volunteersbyopportunity/', views.get_volunteersbyopportunity.as_view(), name='get_volunteersbyopportunity'),
	url(r'^update_request/', views.update_request.as_view(), name='update_request'),
	url(r'^fetch_all_oppo/',views.fetch_all_oppo.as_view(), name='fetch_all_oppo'),
	url(r'^get_opportunity_volunteer_by_user_date/(?P<offset>\d+)/', views.get_opportunity_volunteer_by_user_date.as_view(), name='get_opportunity_volunteer_by_user_date'),
	url(r'^save_opportunity/', views.save_opportunity.as_view(), name='save_opportunity'), 
	url(r'^get_saved_opportunity/', views.get_saved_opportunity.as_view(), name='get_saved_opportunity'),
	url(r'^opportunity_apply/', views.opportunity_apply.as_view(), name='opportunity_apply'),
	url(r'^update_organization/', views.update_organization.as_view(), name='update_organization'),
	#added on 09-01-19
	url(r'^get_coordinator/', views.get_coordinator.as_view(), name='get_coordinator'),
	url(r'^get_volunteersof/', views.get_volunteersof.as_view(), name='get_volunteersof'),
	url(r'^fetch_all_answers/', views.fetch_all_answers.as_view(), name='fetch_all_answers'),
	

	url(r'^remove_save_opportunity/', views.remove_save_opportunity, name='remove_save_opportunity'),
	url(r'^get_opportunities_savedstatus/(?P<offset>\d+)/', views.get_opportunities_savedstatus.as_view(), name='get_opportunities_savedstatus'),
	url(r'^get_myapplied_opportunity/', views.get_myapplied_opportunity.as_view(), name='get_myapplied_opportunity'),
	url(r'^share_opportunity/', views.share_opportunity.as_view(), name='share_opportunity'),
	url(r'^share_opportunity_update/', views.share_opportunity_update, name='share_opportunity_update'),
	url(r'^get_myshared_opportunity/', views.get_myshared_opportunity.as_view(), name='get_myshared_opportunity'),
	#Share opportunity to your organization
	url(r'^get_shared_opportunity_organization/', views.get_shared_opportunity_organization.as_view(), name='get_shared_opportunity_organization'),
	url(r'^get_myposted_opportunity/', views.get_myposted_opportunity.as_view(), name='get_myposted_opportunity'),
	url(r'^get_shared_opportunity/', views.get_shared_opportunity.as_view(), name='get_shared_opportunity'),
    url(r'^update_opportunity/', views.update_opportunity, name='update_opportunity'),
    url(r'^addvolunteerbyowner/', views.addvolunteerbyowner.as_view(), name='addvolunteerbyowner'),
	url(r'^shared_opportunity_organization/', views.shared_opportunity_organization.as_view(), name='shared_opportunity_organization'),
	url(r'^get_volunteers_suggestion/', views.get_volunteers_suggestion.as_view(), name='get_volunteers_suggestion'),
	url(r'^getengage_by_userdate/', views.getengage_by_userdate.as_view(), name='getengage_by_userdate'),
	url(r'^getengage_by_date/', views.getengage_by_date.as_view(), name='getengage_by_date'),
	url(r'^getengage_by_date_new/', views.getengage_by_date_new.as_view(), name='getengage_by_date_new'),

	url(r'^get_organization_by_id/', views.get_organization_by_id.as_view(), name='get_organization_by_id'),

	url(r'^get_user_volunteer/', views.get_user_volunteer.as_view(), name='get_user_volunteer'),
	url(r'^get_oppoptunity_volunteertime/', views.get_oppoptunity_volunteertime, name='get_oppoptunity_volunteertime'),
	url(r'^excel_export/', views.excel_export, name='excel_export'),
	#10.01.19
    url(r'^my_inteer/', views.my_inteer.as_view(), name='my_inteer'),
    url(r'^applicant_sorting/', views.applicant_sorting.as_view(), name='applicant_sorting'),
    url(r'^excel_export_test/', views.excel_export_test, name='excel_export_test'),
    url(r'^excel_export_organization/', views.excel_export_organization, name='excel_export_organization'),
    url(r'^export_organization_report/', views.export_organization_report, name='export_organization_report'),
   	url(r'^export_volunteer_report/', views.export_volunteer_report, name='export_volunteer_report'),
   	url(r'^export_engagethree_report/', views.export_engagethree_report, name='export_engagethree_report'),
   	url(r'^save_opp/', views.save_opp.as_view(), name='save_opp'),
   	url(r'^save_opp_list/', views.save_opp_list.as_view(), name='save_opp_list'),
   	url(r'^delete_volunteer/', views.delete_volunteer.as_view(), name='delete_volunteer'),
   	url(r'^delete_opportunity/', views.delete_opportunity.as_view(), name='delete_opportunity'),
	url(r'^copy_opportunity/', views.copy_opportunity.as_view(), name='copy_opportunity'),
	url(r'^upload_image/', views.upload_image.as_view(), name='upload_image'),
	url(r'^reoccur/', views.reoccur.as_view(), name='reoccur'),
	url(r'^gettest/', views.gettest, name='gettest'),
	url(r'^get_organizationlist/', views.get_organizationlist, name='get_organizationlist'),
	url(r'^get_opportunity_by_organization/(?P<offset>\d+)/',views.get_opportunity_by_organization, name='get_opportunity_by_organization'),
	url(r'^get_test/',views.get_test, name='get_test'),
	url(r'^save_organization/', views.save_organization.as_view(), name='save_organization'),
	url(r'^upload_csv/', views.upload_csv, name='upload_csv'),
	url(r'^edit_opportunity/', views.edit_opportunity.as_view(), name='edit_opportunity'),
	url(r'^upload_opportunity/', views.upload_opportunity, name='upload_opportunity'),
	url(r'^save_contactus/', views.save_contactus, name='save_contactus'),
	url(r'^upload_organization/', views.upload_organization, name='upload_organization'),
	url(r'^approve_all/', views.approve_all.as_view(), name='approve_all'),
	url(r'^get_cordinator_organization/', views.get_cordinator_organization.as_view(), name='get_cordinator_organization'),
	url(r'^get_organization_by_user11/', views.get_organization_by_user11, name='get_organization_by_user11'),
	url(r'^edit_organization/', views.edit_organization.as_view(), name='edit_organization'),
	url(r'^new_export_csv/',views.new_export_csv, name='new_export_csv'),
	url(r'^cronset', views.cronset, name='cronset'),
	url(r'^feedback_send', views.feedback_send, name='feedback_send'),
	url(r'^feedback_submit',views.feedback_submit.as_view(), name='feedback_submit'),
	url(r'^fetch_country',views.fetch_country, name='fetch_country'),
	url(r'^fetch_state',views.fetch_state, name='fetch_state'),

	# url(r'^stripehome', views.stripehome, name='stripehome'),
	# url(r'^charge/', views.charge, name='charge'),
	url(r'^stripehome', views.stripehome, name='stripehome'),
	url(r'^charge/', views.charge.as_view(), name='charge'),
	url(r'^paypalsubscription/', views.get_subscription, name='paypalsubscription'),
	url(r'^paymenthistory/', views.paymenthistory.as_view(), name='paymenthistory'),
	url(r'^user_subscription_details/', views.user_subscription_details.as_view(), name='user_subscription_details'),
	url(r'^subscriptiondelete/', views.subscriptiondelete.as_view(), name='subscriptiondelete'),
	url(r'^custom-user-subscription/', views.customUserSubscription.as_view(), name='custom_user_subscription'),
	url(r'^unlock-package-subscription/', views.unlockPackageSubscription.as_view(), name='unlock_package_subscription'),
	url(r'^stripewebhook/', views.stripewebhook, name='stripewebhook'),
	url(r'^public-key/', views.public_key, name='public-key'),
	url(r'^create-customer/', views.create_customer, name='create-customer'),
	url(r'^subscription/', views.subscription.as_view(), name='confirm_subscription'),
	url(r'^cancel-subscription/', views.cancel_subscription.as_view(), name='cancel_subscription'),
	url(r'^test-upload-image/', views.test_upload_image, name='test_upload_image'),
	# url(r'^ttt/', views.ttt, name='ttt'),
	# url(r'^subscription_details_create/', views.sdc, name='sdc'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]
