# Generated by Django 2.0.2 on 2020-02-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_merge_20200213_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='affiliated_org',
            field=models.IntegerField(default=0),
        ),
    ]
