# Generated by Django 2.0.2 on 2020-01-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_start_date',
            field=models.TextField(null=True),
        ),
    ]
