# Generated by Django 2.0.1 on 2018-02-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_logo',
            field=models.ImageField(null=True, upload_to='banners'),
        ),
    ]
