# Generated by Django 2.0.2 on 2020-02-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_organization_affiliated_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='affiliated_activity_hours',
            field=models.IntegerField(default=0),
        ),
    ]
