# Generated by Django 2.0.2 on 2020-01-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_userprofile_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplandetails',
            name='interval_count',
            field=models.TextField(blank=True, null=True),
        ),
    ]
