# Generated by Django 2.0.2 on 2020-01-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_subscriptionplandetails_interval_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplandetails',
            name='interval_count',
            field=models.IntegerField(default=0),
        ),
    ]
