# Generated by Django 2.0.2 on 2020-01-13 02:01

import adminpanel.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0004_auto_20200110_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlockPayementInformations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.TextField(blank=True, null=True)),
                ('package', models.TextField(blank=True, null=True)),
                ('plan_id', models.TextField(blank=True, null=True)),
                ('plan_type', models.TextField(blank=True, null=True)),
                ('subscription_id', models.TextField(blank=True, null=True)),
                ('subscription_start_date', models.TextField(blank=True, null=True)),
                ('subscription_end_date', models.TextField(blank=True, null=True)),
                ('unlock_start_date', models.TextField(blank=True, null=True)),
                ('unlock_end_date', models.TextField(blank=True, null=True)),
                ('subscribed', models.BooleanField(default=False)),
                ('subscription_response', models.TextField(blank=True, null=True)),
                ('plan_response', models.TextField(blank=True, null=True)),
                ('product_response', models.TextField(blank=True, null=True)),
                ('subscription_mode', models.TextField(blank=True, null=True)),
                ('subscription_ended', models.BooleanField(default=False)),
                ('subscription_deleted', enumfields.fields.EnumField(default=0, enum=adminpanel.models.SubcriptionDeletion, max_length=10)),
                ('subscription_plan_details_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.SubscriptionPlanDetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.UserProfile')),
            ],
        ),
    ]
