# Generated by Django 2.0.2 on 2020-02-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_subscriptionplandetails_amount'),
        ('adminpanel', '0002_banner_banner_logo'),
    ]

    operations = [
    ]
