# Generated by Django 2.0.1 on 2018-02-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_userprofile_activate_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
