# Generated by Django 2.0.1 on 2018-02-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20180205_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='cordinatorrequest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cordinatorrequest',
            name='employee_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
