# Generated by Django 2.0.1 on 2018-04-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_opportunities_interest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='event1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='event2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='event3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='fb_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='irs_rank',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='submission_date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
