# Generated by Django 2.0.1 on 2018-04-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_auto_20180405_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tax_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='web_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
