# Generated by Django 2.0.1 on 2018-04-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_auto_20180405_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunities',
            name='volunteer_id',
        ),
        migrations.AddField(
            model_name='opportunities',
            name='no_of_volunteers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reminders',
            name='before_hour',
            field=models.IntegerField(default=0),
        ),
    ]
