# Generated by Django 2.0.1 on 2018-04-09 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_auto_20180409_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.ActivityCategory')),
                ('opportunity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Opportunities')),
            ],
        ),
    ]
