# Generated by Django 2.0.1 on 2018-04-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_opportunitycategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunities',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
