# Generated by Django 2.0.1 on 2018-04-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_remove_opportunities_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunities',
            name='image',
            field=models.ImageField(null=True, upload_to='opportunity'),
        ),
    ]
