# Generated by Django 2.0.2 on 2019-12-19 22:05

import adminpanel.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_auto_20191217_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='payementinformations',
            name='additional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payementinformations',
            name='subscription_deleted',
            field=enumfields.fields.EnumField(default=0, enum=adminpanel.models.SubcriptionDeletion, max_length=10),
        ),
        migrations.AddField(
            model_name='payementinformations',
            name='subscription_ended',
            field=models.BooleanField(default=False),
        ),
    ]
