# Generated by Django 2.0.2 on 2019-12-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_auto_20191219_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunitycategories',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='opportunitycategories',
            name='opportunity_id',
        ),
        migrations.DeleteModel(
            name='ActivityCategory',
        ),
        migrations.DeleteModel(
            name='OpportunityCategories',
        ),
    ]
